import type { TaskGraph } from "../../../domain/chronos/task-os";

type TaskGraphPreviewProps = {
  graph: TaskGraph;
  capabilityName: string;
};

/** Visual plan generated by Chronos from an objective, before execution begins. */
export function TaskGraphPreview({ graph, capabilityName }: TaskGraphPreviewProps) {
  return (
    <section className="mb-6 overflow-hidden rounded-xl border border-line bg-bg-soft">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-5 py-4">
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.23em] text-chronos">Planner decomposition</div>
          <div className="mt-1 font-serif text-2xl text-ink">Launch startup</div>
        </div>
        <div className="rounded-full border border-line bg-bg px-3 py-1 font-mono text-[10px] uppercase tracking-[0.18em] text-ink-dim">
          {graph.tasks.length} generated tasks
        </div>
      </div>

      <div className="overflow-x-auto px-5 py-5">
        <div className="flex min-w-max items-center gap-2">
          {graph.tasks.map((task, index) => (
            <div key={task.id} className="flex items-center gap-2">
              <div className="w-[160px] shrink-0 rounded-lg border border-line bg-bg p-3 sm:w-[168px]">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[9px] tracking-[0.18em] text-chronos">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                  <span className="h-1.5 w-1.5 rounded-full bg-chronos" />
                </div>
                <div className="mt-3 break-words font-serif text-[16px] leading-snug text-ink sm:text-[17px]">
                  {task.title}
                </div>
                <div className="mt-2 break-all font-mono text-[9px] uppercase tracking-[0.12em] text-ink-faint">
                  {task.capability}
                </div>
              </div>
              {index < graph.tasks.length - 1 && (
                <svg width="16" height="16" viewBox="0 0 16 16" className="shrink-0 text-ink-faint">
                  <path d="M2 8h11M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              )}
            </div>
          ))}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-line bg-bg/40 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.18em] text-ink-faint">
        <span>Chronos resolves registered capabilities automatically</span>
        <span className="hidden h-3 w-px bg-line sm:block" />
        <span className="text-accent-2">{capabilityName}</span>
      </div>
    </section>
  );
}